include: package:pedantic/analysis_options.yaml

analyzer:
    enable-experiment:
    - non-nullable

    errors:
        missing_required_param: error

linter:
    rules:
        - always_put_control_body_on_new_line
