name: vesta
description: Not offical, alternative neptun app

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.0.1+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
#  http: ^0.12.0+2
  background_fetch:
    git:
      url: https://github.com/transistorsoft/flutter_background_fetch
  flutter_local_notifications: ^1.1.3
  fluro:
    git:
      url: https://github.com/theyakka/fluro.git
  url_launcher:
    git:
      url: https://github.com/flutter/plugins.git
      path: packages/url_launcher/url_launcher/
  logger: ^0.9.2
  overlay_support:
    git:
      url: https://github.com/boyan01/overlay_support
      version: ^1.0.0
  path_provider:
    git:
      url: https://github.com/flutter/plugins
      path: packages/path_provider/path_provider
      version: ^1.6.5
  flutter_widget_from_html_core:
    git:
      url: https://github.com/daohoangson/flutter_widget_from_html
      path: packages/core
  dio: ^3.0.0
  dio_cookie_manager: ^1.0.0
  universal_io: ^1.0.0
  universal_html: ^1.0.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  pedantic: ^1.9.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:
    git:
      url: https://github.com/fluttercommunity/flutter_launcher_icons


flutter_icons:
  android: "launcher_icon"
  ios: "launcher_icon"
  adaptive_icon_background: "#ffffff"
  image_pathadaptive_icon_foreground: "assets/icon/vesta.svg"
  image_path: "assets/icon/vesta.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/i18n/localization_en.json
    - assets/i18n/localization_hu.json
    - assets/icon/vesta.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
